Fixed visibility of comments.
hydronautics-team/Hydrolib pull request #9
Opened 2024-10-25 17:20 UTC by glebmih

Исправил видимость названий. Добавил разъемы: XT30, CWF-3. Сделал общие УГО для разъемов с одинаковым числом выводов.

2024-10-26 13:24 UTC, SeaJackal submitted a review, later dismissed

2024-10-26 13:24 UTC, SeaJackal commented on Footprints/Connectors/XT30.PcbLib
Обрати внимание на десигнаторы на посадочном месте. По десигнаторам альтиум будет соотносить пины на УГО и посадочном месте, так что они должны совпадать. У XT плюс обычно называется первым контактом.

2024-10-26 13:24 UTC, SeaJackal commented on Footprints/Connectors/XT30.PcbLib
Будет здорово, если посмотришь на snapeda 3d модель разъёма. Всегда приятно её иметь

2024-10-26 13:24 UTC, SeaJackal commented on Footprints/Connectors/XT30.PcbLib
И ещё один пункт. Хорошей практикой является делать пад на первом пине квадратным. Тогда по плате можно легко его узнать, даже если не видно шелкографии. Имеет смысл и нам так сделать

2024-10-26 13:24 UTC, SeaJackal commented on Footprints/Connectors/XT30.PcbLib
Если не найдётся там, то поэкспериментируй с grubcad. Нашёл там такое, может быть подойдёт https://grabcad.com/library/xt30-connector-1

2024-11-01 19:06 UTC, glebmih commented on Footprints/Connectors/XT30.PcbLib
Поправил

2024-11-01 19:07 UTC, glebmih commented on Footprints/Connectors/XT30.PcbLib
Нашел модельку на snapeda, добавил ее

2024-11-01 19:07 UTC, glebmih commented on Footprints/Connectors/XT30.PcbLib
Сделал

2024-11-03 12:53 UTC, SeaJackal requested changes

2024-11-03 12:53 UTC, SeaJackal commented on Footprints/Connectors/XT30.PcbLib
Добавь этот файл в проект библиотеки, пожалуйста

2024-11-03 13:37 UTC, glebmih commented on Footprints/Connectors/XT30.PcbLib
Добавил

2024-11-03 13:38 UTC, SeaJackal approved these changes

2024-11-03 13:38 UTC, merged